# Generated by Django 3.2.18 on 2023-10-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=0)),
                ('pump', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Башня',
                'verbose_name_plural': 'Башня',
            },
        ),
        migrations.CreateModel(
            name='TowerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=None)),
                ('is_pumping', models.BooleanField(default=None)),
            ],
            options={
                'verbose_name': 'Історія',
                'verbose_name_plural': 'Історія',
            },
        ),
    ]
