# Generated by Django 3.2.18 on 2023-10-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tower',
            old_name='uuid',
            new_name='name',
        ),
    ]
